### PR TITLE
[WIP] HAWKULAR-1275 - Changes needed for hServices integration

### PR DESCRIPTION
**Pull request by lucasponce**
Continue tasks started in #249 but using a hawkular-1275 branch as @jshaughn needs also to sync with his work and probably we can't commit separate.
So consolidating changes for hawkular-1275 on this branch.
Probably same with others repos related to MiQ work.

### CODE REVIEW

**Comment by lucasponce** [comment]
Do not merge yet, as we need to finish tasks in the provider to identify if we need additional changes here.
Once all changes are clear, before to submit on other MiQ repos we need to release a new gem.
This is a WIP PR, so new commits and additional changers may be expected.

**Comment by lucasponce** [comment]
@cfcosta I moved the previous PR to this one.

/cc @jshaughn @israel-hdez @josejulio

**Comment by lucasponce** [comment]
Also, note that online tests are not yet fixed as we haven't modified in this branch the Travis CI config for live tests.
Some tests can be tricky to run on live mode, as so features have changed and we would need to query additional info.
So, I propose to address live tests in a following task.

**Comment by jshaughn** [comment]
This is superseded by https://github.com/hawkular/hawkular-client-ruby/pull/252, so closing.

**Pull request closed without merging**
