### PR TITLE
issue #35 - uber-client

### PR DESCRIPTION
**Pull request by jkremser**
adding a facade for all the hawkular component clients, so that one could call everything from 1 place, this should also fix the issue #23

There are 2 ways to use the "uber client":
 `uber_client.inventory.get_tenant` or `uber_client.inventory_get_tenant` or in more general `uber_client.X.Y` and `uber_client.X_Y` where `X` is `{inventory, metrics, alerts, tokens, operations}` and `Y` is a method on `X` client

### CODE REVIEW

**Comment by jkremser** [comment]
Oh, this should go to the 0.3.0, so I'll close this PR and push it to a new `0.3.0` branch, sorry for confusion

**Comment by jkremser** [comment]
@pilhuhn can you please give me the write access to this repo, or create the `0.3.0` branch? I can't create a PR for non-existent branch.

**Comment by pilhuhn** [comment]
On 22 Mar 2016, at 22:33, Jirka Kremser wrote:

> @pilhuhn can you please give me the write access to this

I did so.

**Comment by pilhuhn** [comment]
Btw I don't like the 'uber' as we are changing the namespace in 0.3.0, it should just be 'client' or so.

**Pull request closed without merging**
