### PR TITLE
Supporting string metrics

### PR DESCRIPTION
**Pull request by rubenvp8510**
I added some specs to @pilhuhn work.

### CODE REVIEW

**Comment by josejulio** [comment]
Does strings use percentiles [1] or is like availabilities [2] ? 

[1] https://github.com/rubenvp8510/hawkular-client-ruby/blob/a7238af5bc7dd1e21e6427f8d93e8450599c6aab/lib/hawkular/metrics/metric_api.rb#L156
[2] https://github.com/rubenvp8510/hawkular-client-ruby/blob/a7238af5bc7dd1e21e6427f8d93e8450599c6aab/lib/hawkular/metrics/metric_api.rb#L287

**Comment by rubenvp8510** [comment]
good observation @josejulio  it doesn't have percentiles, and I think it doesn't have budgets either.
I'll review it and remove those parameters if needed.

**Comment by josejulio** [comment]
LGTM

**Comment by josejulio** [comment]
Fixes #144

**Pull request merged**
