### PR TITLE
HAWKULAR-1205 - Adds the ability to assign tags to existing alerts.

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by josejulio** [comment]
@rubenvp8510 could you please review?

**Comment by lucasponce** [comment]
@josejulio could you add the counterpart DELETE tag endpoint on this PR too ?
http://www.hawkular.org/docs/rest/rest-alerts.html#DELETE__tags

Then we will cover the whole use case which is basically to add/remove custom tags from ManageIQ.

Thanks !

**Comment by josejulio** [comment]
> @josejulio could you add the counterpart DELETE tag endpoint on this PR too ?
> http://www.hawkular.org/docs/rest/rest-alerts.html#DELETE__tags
> 
> Then we will cover the whole use case which is basically to add/remove custom tags from ManageIQ.
> 
> Thanks !

Sure

**Comment by josejulio** [comment]
@moolitayer Is this what you need?

**Comment by moolitayer** [comment]
Looks exactly like what I need. Thanks @josejulio!

ps @josejulio @lucasponce we would need a new version of the client and an update in Miq,
I can send the later just let me know
Thanks again

**Pull request merged**
