### PR TITLE
update tests to be compatible with latest h-alerts (1.5.1) in h-services

### PR DESCRIPTION
**Pull request by jshaughn**
- new field ActionDefinition.global
- the alerts email plugin is no longer explicitly deployed, it is now
  embedded in hawkular-metrics.ear.

@josejulio Please review.  Note, I haven't really tested these changes (I'm not sure how).  The aren't expected to pass unless run against the Services PR with the updates.  Let me know if there is something I can do to validate.

### CODE REVIEW

**Comment by josejulio** [comment]
The changes look good. 

I guess that you already tested them because your cassettes are updated (unless you manually edited).

Anyway we should merge this one once Hawkular-services related PR is already merged.

In case you haven't been able to test on the services-PR
You can execute:
`VCR_OFF=1 bundle exec rspec spec/integration/alerts_spec.rb:188`
and
`VCR_OFF=1 bundle exec rspec spec/integration/operations_spec.rb:191`

while having Hawkular services running on `localhost:8080`

**Comment by jshaughn** [comment]
@josejulio Yes, I was able to test against my hServices branch locally and update the cassettes via VCR_UPDATE=1.  Things are passing, so, as you say, I think we should merge the services PR and then this one.

**Comment by jshaughn** [comment]
@josejulio or @pilhuhn, The hServcices PR was merged so please merge this as well. Thanks!

**Comment by pilhuhn** [comment]
Shouldn't this then succeed against a live server? And also without server?

**Comment by jshaughn** [comment]
Yes, it should succeed without a live server and should now succeed against hServices master.  I don't think it has been run against the latest live server, let me restart the test then...

**Comment by jshaughn** [comment]
@pilhuhn @josejulio I'm not exactly sure what hServices this runs against, the failure seems to me that it still runs against an older hServices image (pilhun:latest?).  I don't know, I'm fairly sure the specs are now compatible with what is in master.  Perhaps you guys can figure out what's wrong and whether this should be merged.  I'm happy to help, just not sure what to do.

**Comment by josejulio** [comment]
@jshaughn is indeed trying to use pilhun:latest, see https://github.com/hawkular/hawkular-client-ruby/blob/master/docker-compose.yml#L2
Does H-services publish one too?

**Comment by pilhuhn** [comment]
Well, pilhuhn:latest is the latest release. Even if there would be an 
official one, we should still test the ruby client against a release 
version and not arbitrary master, as otherwise we would have too many 
moving parts


Am 2. Februar 2017 5:44:50 nachm. schrieb Josejulio Martínez 
<notifications@github.com>:

**Comment by jshaughn** [comment]
@pilhuhn @josejulio OK, then if I understand this correctly, this PR needs to wait until the next hServices release goes out an pilhuhn:latest is updated.  At that time the PR should pass all tests.  For now it will only pass the cassette test using the cassettes supplied in the PR.  I will leave the DNM label in place until the next release goes out.  Thanks, let me know if this is incorrect.

**Comment by josejulio** [comment]
That seems to be correct, Thanks!

**Comment by pilhuhn** [comment]
This now works with hawkular-services 0.31

**Pull request merged**
