### PR TITLE
Operation add datasource and remove datasource fails if running on th…

### PR DESCRIPTION
**Pull request by josejulio**
…e newest hawkular-services container

We now detect (currently via env variable) if we are running in one and expects those tests to fail.

### CODE REVIEW

**Comment by josejulio** [comment]
I'll try to get the server [immutable flag](https://github.com/hawkular/hawkular-agent/pull/286) instead of setting a value.

**Comment by josejulio** [comment]
@pilhuhn This tries to fetch the "In Container" property from the agent to determine how to behave on a couple of operation specs. If said property isn't found, we default to "In Container" = false.

**Comment by pilhuhn** [comment]
I'll merge that now. In-Container flag will be provided for container builds once https://github.com/hawkular/hawkular-services/pull/122 is merged.

**Comment by josejulio** [comment]
There seems to be new errors there, I'll check it and follow this up.

**Pull request merged**
